# Generated by Django 5.0.1 on 2024-01-07 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_searchquery'),
    ]

    operations = [
        migrations.AddField(
            model_name='splunkobject',
            name='action_type',
            field=models.CharField(choices=[('delete', 'delete'), ('Share', 'Share')], max_length=20, null=True),
        ),
    ]
