# Generated by Django 5.0.1 on 2024-01-07 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_splunkobject_action_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='splunkobject',
            name='custom_fields',
            field=models.CharField(choices=[('top secret', 'Top Secret'), ('top secret/sci', 'Top Secret/SCI'), ('secret', 'Secret'), ('confidential', 'Confidential'), ('unclassified', 'Unclassified')], max_length=20, null=True),
        ),
    ]
