# Generated by Django 5.0.1 on 2024-01-08 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_splunkobject_action_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='splunkobject',
            name='action_type',
            field=models.CharField(choices=[('delete', 'delete'), ('Share', 'Share')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='splunkobject',
            name='custom_fields',
            field=models.CharField(choices=[('top secret', 'Top Secret'), ('top secret/sci', 'Top Secret/SCI'), ('secret', 'Secret'), ('confidential', 'Confidential'), ('unclassified', 'Unclassified')], max_length=20, null=True),
        ),
    ]
